### ISSUE TITLE
Kaitlyn Hopkins

### ISSUE THREAD

**Issue by kaitlynehopkins** [umiami-web-design/final-project#6]
http://kaitlynhopkins.me/

**Comment by ebrown15** [comment]
Great job! Grade is in CaneLink. One issue: On your design page, the Facebook Web Advertisement image is missing. :(

**Comment by kaitlynehopkins** [comment]
Wait it was there!!! Maybe I messed something up between when I showed it to you and now😔 I’ll make sure to fix it so it’s good just for the future! Thank you for all your help again! Have an amazing holidays!
