### ISSUE TITLE
Portia Baudisch

### ISSUE THREAD

**Issue by portiabaudisch** [umiami-web-design/final-project#7]
portiabaudisch.me

**Comment by ebrown15** [comment]
Grade is posted in CaneLink.

**Comment by portiabaudisch** [comment]
Hi Professor Brown,

I checked Canelink and it says 0 for my grade for the portfolio.

Can you let me know what I got?

Also, I forget what you had said but will you be at the Comm school tomorrow around noon so I can stop by and say goodbye?

Thank you!

Portia Baudisch

On Dec 12, 2018, at 1:45 PM, Erin Brown <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #7<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fumiami-web-design%2Ffinal-project%2Fissues%2F7&data=02%7C01%7Cpmb33%40miami.edu%7C1799fbf8c35048918dfa08d66061ebdb%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636802371018962169&sdata=KnjpCALU3P0wXJ5qSgzjAd%2B63hYEcVO%2FsZmr9A%2B9BIw%3D&reserved=0>.
